### ISSUE TITLE
docsearch not working

### ISSUE THREAD

**Issue by likui628** [sudongyuer/learn-eslint#11]
It seems that the doc search not working. 

<img width="326" alt="image" src="https://user-images.githubusercontent.com/90845831/176993953-80a9536c-59ce-4af3-b007-f79a3ad03664.png">

**Comment by sudongyuer** [comment]
Yes i am working on it , need few days

**Comment by likui628** [comment]
> 
my old iron, maybe I can help.

**Comment by sudongyuer** [comment]
glad to hear that
